apps/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    # Examples:
    # url(r'^$', 'apps.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^books_cbv/', include('books_cbv.urls', namespace='books_cbv')),
    url(r'^books_fbv/', include('books_fbv.urls', namespace='books_fbv')),
    url(r'^books_fbv_user/', include('books_fbv_user.urls', namespace='books_fbv_user')),
    url(r'^$', 'apps.views.home'),
]

books_cbv/urls.py
from django.conf.urls import patterns, url

from books_cbv import views

urlpatterns = patterns('',
  url(r'^$', views.BookList.as_view(), name='book_list'),
  url(r'^new$', views.BookCreate.as_view(), name='book_new'),
  url(r'^edit/(?P<pk>\d+)$', views.BookUpdate.as_view(), name='book_edit'),
  url(r'^delete/(?P<pk>\d+)$', views.BookDelete.as_view(), name='book_delete'),
)

books_fbv/urls.py
from django.conf.urls import patterns, url

from books_fbv import views

urlpatterns = patterns('',
  url(r'^$', views.book_list, name='book_list'),
  url(r'^new$', views.book_create, name='book_new'),
  url(r'^edit/(?P<pk>\d+)$', views.book_update, name='book_edit'),
  url(r'^delete/(?P<pk>\d+)$', views.book_delete, name='book_delete'),
)

books_fbv_user/urls.py
from django.conf.urls import patterns, url

from books_fbv_user import views

urlpatterns = patterns('',
  url(r'^$', views.book_list, name='book_list'),
  url(r'^new$', views.book_create, name='book_new'),
  url(r'^edit/(?P<pk>\d+)$', views.book_update, name='book_edit'),
  url(r'^delete/(?P<pk>\d+)$', views.book_delete, name='book_delete'),
)

books_cbv/models.py
from django.db import models
from django.core.urlresolvers import reverse


class Book(models.Model):
    name = models.CharField(max_length=200)
    pages = models.IntegerField()

    def __unicode__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('books_cbv:book_edit', kwargs={'pk': self.pk})

books_fbv/models.py
from django.db import models
from django.core.urlresolvers import reverse


class Book(models.Model):
    name = models.CharField(max_length=200)
    pages = models.IntegerField()

    def __unicode__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('books_fbv:book_edit', kwargs={'pk': self.pk})

books_fbv_user/models.py
from django.db import models
from django.core.urlresolvers import reverse
from django.conf import settings

class Book(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL)
    name = models.CharField(max_length=200)
    pages = models.IntegerField()

    def __unicode__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('books_fbv_user:book_edit', kwargs={'pk': self.pk})

apps/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse

def home(request):
    html = """
    <h1>Django CRUD Example</h1>
    <a href="/books_cbv/">Class Based Views</a><br>
    <a href="/books_fbv/">Function Based Views</a><br>    
    <a href="/books_fbv_user/">Function Based Views with User Access</a><br>    
    """
    return HttpResponse(html)

books_cbv/views.py
from django.http import HttpResponse
from django.views.generic import TemplateView,ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.core.urlresolvers import reverse_lazy

from books_cbv.models import Book

class BookList(ListView):
    model = Book

class BookCreate(CreateView):
    model = Book
    fields = ['name', 'pages']
    success_url = reverse_lazy('books_cbv:book_list')

class BookUpdate(UpdateView):
    model = Book
    fields = ['name', 'pages']
    success_url = reverse_lazy('books_cbv:book_list')

class BookDelete(DeleteView):
    model = Book
    success_url = reverse_lazy('books_cbv:book_list')

books_fbv/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.forms import ModelForm

from books_fbv.models import Book

class BookForm(ModelForm):
    class Meta:
        model = Book
        fields = ['name', 'pages']

def book_list(request, template_name='books_fbv/book_list.html'):
    book = Book.objects.all()
    data = {}
    data['object_list'] = book
    return render(request, template_name, data)

def book_create(request, template_name='books_fbv/book_form.html'):
    form = BookForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect('books_fbv:book_list')
    return render(request, template_name, {'form':form})

def book_update(request, pk, template_name='books_fbv/book_form.html'):
    book= get_object_or_404(Book, pk=pk)
    form = BookForm(request.POST or None, instance=book)
    if form.is_valid():
        form.save()
        return redirect('books_fbv:book_list')
    return render(request, template_name, {'form':form})

def book_delete(request, pk, template_name='books_fbv/book_confirm_delete.html'):
    book= get_object_or_404(Book, pk=pk)    
    if request.method=='POST':
        book.delete()
        return redirect('books_fbv:book_list')
    return render(request, template_name, {'object':book})

books_fbv_user/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from django.forms import ModelForm

from books_fbv_user.models import Book

class BookForm(ModelForm):
    class Meta:
        model = Book
        fields = ['name', 'pages']

@login_required
def book_list(request, template_name='books_fbv_user/book_list.html'):
    if request.user.is_superuser:
        book = Book.objects.all()
    else:
        book = Book.objects.filter(user=request.user)
    data = {}
    data['object_list'] = book
    return render(request, template_name, data)

@login_required
def book_create(request, template_name='books_fbv_user/book_form.html'):
    form = BookForm(request.POST or None)
    if form.is_valid():
        book = form.save(commit=False)
        book.user = request.user
        book.save()
        return redirect('books_fbv_user:book_list')
    return render(request, template_name, {'form':form})

@login_required
def book_update(request, pk, template_name='books_fbv_user/book_form.html'):
    if request.user.is_superuser:
        book= get_object_or_404(Book, pk=pk)
    else:
        book= get_object_or_404(Book, pk=pk, user=request.user)
    form = BookForm(request.POST or None, instance=book)
    if form.is_valid():
        form.save()
        return redirect('books_fbv_user:book_list')
    return render(request, template_name, {'form':form})

@login_required
def book_delete(request, pk, template_name='books_fbv_user/book_confirm_delete.html'):
    if request.user.is_superuser:
        book= get_object_or_404(Book, pk=pk)
    else:
        book= get_object_or_404(Book, pk=pk, user=request.user)
    if request.method=='POST':
        book.delete()
        return redirect('books_fbv_user:book_list')
    return render(request, template_name, {'object':book})

books_cbv/templates/books_cbv/book_confirm_delete.html
<form method="post">{% csrf_token %}
    Are you sure you want to delete "{{ object }}" ?
    <input type="submit" value="Submit" />
</form>

books_cbv/templates/books_cbv/book_form.html
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit" />
</form>

books_cbv/templates/books_cbv/book_list.html
<h1>Books CBV</h1>
<ul>
    {% for book in object_list %}
    <li>{{ book.name }}  ({{ book.pages }} Pages)
    <a href="{% url 'books_cbv:book_edit' book.id %}">edit</a>
    <a href="{% url 'books_cbv:book_delete' book.id %}">delete</a>
    </li>
    {% endfor %}
</ul>

<a href="{% url 'books_cbv:book_new' %}">New</a>

books_fbv/templates/books_fbv/book_confirm_delete.html
<form method="post">{% csrf_token %}
    Are you sure you want to delete "{{ object }}" ?
    <input type="submit" value="Submit" />
</form>

books_fbv/templates/books_fbv/book_form.html
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit" />
</form>

books_fbv/templates/books_fbv/book_list.html
<h1>Books FBV</h1>
<ul>
    {% for book in object_list %}
    <li>{{ book.name }}  ({{ book.pages }} Pages)
    <a href="{% url 'books_fbv:book_edit' book.id %}">edit</a>
    <a href="{% url 'books_fbv:book_delete' book.id %}">delete</a>
    </li>
    {% endfor %}
</ul>

<a href="{% url 'books_fbv:book_new' %}">New</a>

books_fbv_user/templates/books_fbv_user/book_confirm_delete.html
<form method="post">{% csrf_token %}
    Are you sure you want to delete "{{ object }}" ?
    <input type="submit" value="Submit" />
</form>

books_fbv_user/templates/books_fbv_user/book_form.html
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit" />
</form>

books_fbv_user/templates/books_fbv_user/book_list.html
<h1>Books FBV User</h1>
<ul>
    {% for book in object_list %}
    <li>{{ book.name }}  ({{ book.pages }} Pages)
    <a href="{% url 'books_fbv_user:book_edit' book.id %}">edit</a>
    <a href="{% url 'books_fbv_user:book_delete' book.id %}">delete</a>
    </li>
    {% endfor %}
</ul>

<a href="{% url 'books_fbv_user:book_new' %}">New</a>